import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/link'

import styles from "../../styles/pages/League_pages.module.scss"


import logo_champions_league from '../../img/logo_champions_league.png'
import icon_calendar from '../../img/icon_calendar.png'
import icon_classement from '../../img/icon_classement.png'
import icon_resultats from '../../img/icon_result.png'
import icon_teams from '../../img/icon_teams.png'

const ChampionsLeague = () => {
  return (
    <div className={styles.main_container}>
      <Head>
        <title>EFL | Champions League | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon_ball.ico" />
      </Head>
      <div className={styles.logo_container}>
        <Image src={logo_champions_league}/>
      </div>
      <div className={styles.cards_container}>
        <Link href="/champions_league/results">
        <div className={styles.card}>
          <div className={styles.icon_container}>
            <Image src={icon_resultats}/>
          </div>
          <h2>Résultats</h2>
        </div>
        </Link>
        <Link href="/champions_league/ranking">
        <div className={styles.card}>
          <div className={styles.icon_container}>
            <Image src={icon_classement}/>
          </div>
          <h2>Classement</h2>
        </div>
        </Link>
        <Link href="/champions_league/calendar">
        <div className={styles.card}>
          <div className={styles.icon_container}>
            <Image src={icon_calendar}/>
          </div>
          <h2>Calendrier</h2>
        </div>
        </Link>
        <Link href="/champions_league/teams">
        <div className={styles.card}>
          <div className={styles.icon_container}>
            <Image src={icon_teams}/>
          </div>
          <h2>Equipes</h2>
        </div>
        </Link>
        </div>

    </div>
  )
}

export default ChampionsLeague